[package]
name = "nysvpn-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
chacha20poly1305 = "0.10"
tun = { version = "0.6", features = ["async"] }
tokio-util = "0.7"
rand_core = "0.6"
